### ISSUE TITLE
SizeMultiplier property in view not working

### ISSUE THREAD

**Issue by vitorOta** [vlad1m1r990/Lemniscate#4]
SizeMultiplier not working when I put `app:sizeMultiplier="2.0"` 
To solve this, I use `progressView.setSizeMultiplier(2f);`

**Comment by vlad1m1r990** [comment]
Fixed with the [Release 1.4.1](https://github.com/vlad1m1r990/Lemniscate/releases/tag/1.4.1).
Thank you very much for opening the issue 🍰!
