### ISSUE TITLE
Animation inside scrollview is not visible.

### ISSUE THREAD

**Issue by k-gintaras** [vlad1m1r990/Lemniscate#5]
If you put animation inside linear layout that is inside scrollview, it will not be shown, but outside of scrollview it is visible.

**Comment by vlad1m1r990** [comment]
Fixed with the [Release 1.4.2](https://github.com/vlad1m1r990/Lemniscate/releases/tag/1.4.2).
Thank you very much for opening the issue 🎁!

**Comment by k-gintaras** [comment]
Whoa, I am excited and happy that it helped, this is my first "issue" and it got noticed! Thank you:)

**Comment by vlad1m1r990** [comment]
Thank you for using my library 😄 . If you need any support feel free to contact me. Also, all suggestions are welcome.
